name: Django Tests

on: [push, pull_request]  # Run on every push & pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install pytest pytest-django
        pip install -r requirements.txt  # Install project dependencies

    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: travelapp.settings  # Replace with your actual project name
      run: |
        python manage.py makemigrations
        python manage.py migrate  
        pytest  
